version: '3.9'
services:
  backend:
    build:
      context: ./university-management-backend
    volumes:
      - ./university-management-backend:/app
    ports:
      - "8000:8000"


  frontend:
    build:
      context: ./university-management-frontend
    volumes:
      - ./university-management-frontend:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000  # Docker network URL for backend
